{
    'name': 'Rapports des ventes',
    'version': '12.0.1.0.1',
    'summary': 'Rapports des ventes',
    'author': 'Sakhri Rabie',
    'maintainer': 'Sakhri Rabie',
    'Company': 'Le Programmeur',
    'website': 'http://rabie.co',
    'depends': ['base','sale_management','crm_operation'],
    'license': 'LGPL-3',
    'category': 'CRM',
    'data':[
        'wizards/sale_report_wizard.xml',
        'reports/sale_reports.xml',
        'reports/sale_report_view.xml',
    ],
    'images': ['static/description/logo_r.jpg'],
    'price': 0.0,
    'currency': 'DZD',
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 5,
}
